-- CREATE
CREATE TABLE MEMBER
(
    ID          VARCHAR2(50),
    PWD         NVARCHAR2(50),
    NAME        NVARCHAR2(50),
    GENDER      NCHAR(2),      -- 남성, 여성  UTF
    AGE         NUMBER(3),
    BIRTHDAY    CHAR(10),     -- 2000-01-02
    PHONE       CHAR(13),     -- 010-1234-2345
    REGDATE     DATE
);

INSERT INTO MEMBER(GENDER) VALUES('남성');
SELECT LENGTHB(GENDER) FROM MEMBER;

DROP TABLE MEMBER;

SELECT LENGTH('ab') FROM DUAL;   -- 2
SELECT LENGTHB('ab') FROM DUAL;  -- 2

SELECT LENGTH('한글') FROM DUAL;  -- 2
SELECT LENGTHB('한글') FROM DUAL; -- 6(3byte 사용)

SELECT * FROM NLS_DATABASE_PARAMETERS;


-- ALTER 
ALTER TABLE MEMBER MODIFY ID NVARCHAR2(50); -- 데이터타입 수정
ALTER TABLE MEMBER DROP COLUMN AGE;         -- 속성컬럼 삭제
ALTER TABLE MEMBER ADD EMAIL VARCHAR2(200); -- 속성컬럼 추가



-- 수업용 테이블 구성
CREATE TABLE NOTICE
(
    ID          NUMBER,
    TITLE       NVARCHAR2(100),
    WRITER_ID   NVARCHAR2(50),
    CONTENT     CLOB,
    REGDATE     TIMESTAMP,
    HIT         NUMBER,
    FILES       NVARCHAR2(1000)
);

CREATE TABLE "COMMENT"  -- COMMENT는 이미 예약된 단어(예약어)
(
    ID          NUMBER,
    CONTENT     NVARCHAR2(2000),
    REGDATE     TIMESTAMP,
    WRITER_ID   NVARCHAR2(50),
    NOTICE_ID   NUMBER
);

CREATE TABLE ROLE
(
    ID          VARCHAR(50),
    DESCRIPTION VARCHAR2(500)
);

CREATE TABLE MEMBER_ROLE
(
    MEMBER_ID   NVARCHAR2(50),
    ROLE_ID     VARCHAR(50)
);











