-- 선수 테이블 생성
CREATE TABLE PLAYER (
PLAYER_ID       CHAR(7) NOT NULL,
PLAYER_NAME     VARCHAR2(20) NOT NULL,
TEAM_ID         CHAR(3) NOT NULL,
E_PLAYER_NAME   VARCHAR2(40),
NICKNAME        VARCHAR2(30),
JOIN_YYYY       CHAR(4),
POSITION        VARCHAR2(10),
BACK_NO         NUMBER(2),
NATION          VARCHAR2(20),
BIRTH_DATE      DATE,
SOLAR           CHAR(1),
HEIGHT          NUMBER(3),
WEIGHT          NUMBER(3),

CONSTRAINT PLAYER_PK PRIMARY KEY (PLAYER_ID)
--,
--CONSTRAINT PLAYER_FK FOREIGN KEY (TEAM_ID) REFERENCES TEAM(TEAM_ID)
);
-- 제약조건 추가(외래키)
ALTER TABLE PLAYER
ADD CONSTRAINT PLAYER_FK FOREIGN KEY (TEAM_ID) REFERENCES TEAM(TEAM_ID)
;
-- 제약조건 삭제(외래키)
ALTER TABLE PLAYER
DROP CONSTRAINT PLAYER_FK
;
-- 테이블 확인
DESCRIBE PLAYER
;



-- 팀 테이블 생성
CREATE TABLE TEAM (
TEAM_ID         CHAR(3) NOT NULL,
REGION_NAME     VARCHAR2(8) NOT NULL,
TEAM_NAME       VARCHAR2(40) NOT NULL,
E_TEAM_NAME     VARCHAR2(50),
ORIG_YYYY       CHAR(4),
STADIUM_ID      CHAR(3) NOT NULL,
ZIP_CODE1       CHAR(3),
ZIP_CODE2       CHAR(3),
ADDRESS         VARCHAR2(80),
DDD             VARCHAR2(3),
TEL             VARCHAR2(10),
FAX             VARCHAR2(10),
HOMEPAGE        VARCHAR2(50),
OWNER           VARCHAR2(10),
CONSTRAINT TEAM_PK PRIMARY KEY (TEAM_ID)

--,
--CONSTRAINT TEAM_FK FOREIGN KEY (STADIUM_ID) REFERENCES STADIUM(STADIUM_ID) 
);
-- 제약조건 추가(외래키)
ALTER TABLE TEAM
ADD CONSTRAINT TEAM_FK FOREIGN KEY (STADIUM_ID) REFERENCES STADIUM(STADIUM_ID)
;
-- 테이블 확인
DESCRIBE TEAM
;



-- AS SELECT를 사용한 테이블 생성
-- 이렇게 생성하면 설정해놓은 제약조건은 사라지므로
-- ALTER를 이용하여 재설정해줘야 한다.
CREATE TABLE TEAM_TEMP
AS SELECT * FROM TEAM
;
-- 칼럼 삭제 (TEAM_TEMP.DDD)
ALTER TABLE TEAM_TEMP
DROP COLUMN DDD
;
-- 칼럼 수정 (TEAM_TEMP.ORIG_YYYY)
ALTER TABLE TEAM_TEMP
MODIFY (ORIG_YYYY VARCHAR(8) DEFAULT '20020129' NOT NULL)
;
-- 칼럼 이름 재설정
ALTER TABLE TEAM_TEMP
RENAME COLUMN TEAM_ID TO TEMP_ID
;
ALTER TABLE TEAM_TEMP
RENAME COLUMN TEMP_ID TO TEAM_ID
;
-- 확인
DESCRIBE TEAM_TEMP
;

-- 테이블 이름 재설정
RENAME TEAM_TEMP TO TEAM_RENAMED
;
DESC TEAM_RENAMED
;

-- TRUNCATE:
-- 테이블 자체가 삭제되는 것은 아님.
-- 해당 테이블에 들어있던 모든 행이 제거, 저장공간을 재사용 가능하도록 해제.
TRUNCATE TABLE TEAM_RENAMED
;

-- 테이블 삭제
-- CASCADE CONSTRAINTS: 
-- 관계에 있는 참조되는 제약조건에 대해서도 삭제하겠다.
DROP TABLE TEAM_RENAMED CASCADE CONSTRAINTS
;
DESC TEAM_RENAMED
;



